---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .eslintrc
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "bin/configtest"
  - "**.js"
  - "**.md"
exclude_paths:
  - .circleci/
  - .eslintrc.js
