version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            - dependencies-cache  # fallback to using the latest cache if no exact match is found

      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p cclimate/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cclimate/cc-test-reporter
            chmod +x ./cclimate/cc-test-reporter

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless yarn
            yarn

      - persist_to_workspace:
          root: ./
          paths: 
            - ./

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

            
  check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      - run:
          name: explore dir
          command: |
            echo "ls -al"
            ls -al 

workflows:
  version: 2
  release_dev:
    jobs:
      - build:
          context: aws-sls
      - check:
          requires:
            - build
        
